### ISSUE TITLE
Link to join slack is hard to find

### ISSUE THREAD

**Issue by kylepeeler** [indyhackers/indyhackers.org#101]
The IndyHackers slack community is very active and is a great way to inform others in the Indy tech community. We should add a button to the home page to join the slack channel. Right now it is very hard to find the link to join... (I didn't even know the Slack channel existed until my coworker showed me 🤯).

The button would link to [this app](https://indyhackers-slack.herokuapp.com/).

I am planning on submitting a PR to address this, is there any style guidelines/design constraints that need to be taken into account before starting this?

**Comment by mileszs** [comment]
<img width="1270" alt="Screen Shot 2020-03-03 at 2 08 29 PM" src="https://user-images.githubusercontent.com/2425/75810387-80f0ee80-5d58-11ea-9727-0a6f74ca1863.png">

Good idea. I'd even be in favor of replacing one of these (currently outdated) top two boxes with a short description and link to the org. What do you think?

**Comment by illbzo1** [comment]
<img width="1013" alt="Screen Shot 2020-03-03 at 2 22 09 PM" src="https://user-images.githubusercontent.com/27860/75812019-797f1480-5d5b-11ea-9f28-9a38b645ec2a.png">

Suggested copy and information for the slack button.

**Comment by mileszs** [comment]
<img width="1044" alt="Screen Shot 2020-10-06 at 2 48 26 PM" src="https://user-images.githubusercontent.com/2425/95246867-1bc81480-07e3-11eb-9eb6-8c78a7953e38.png">

I think putting it side-by-side with The Hackies on our current homepage would be best for now!

**Comment by endifmedia** [comment]
I like to grab this one. #hacktoberfest

**Comment by armilam** [comment]
The new link for signing up for slack is https://slack.indyhackers.org
