### ISSUE TITLE
Migrate the app to puma

### ISSUE THREAD

**Issue by t27duck** [indyhackers/indyhackers.org#112]
Puma is kinda becoming the de facto web server to serve Rails apps nowadays as it's become the default server for new Rails apps. This app shouldn't be doing anything that isn't thread-safe, so it should be no real issue to switch.

**Comment by mileszs** [comment]
Is it simply a matter of switching gems and changing the Procfile, @t27duck ? I would think so, but it's been a while since I've needed to make the switch.

**Comment by t27duck** [comment]
Switch the gems, probably source a config/puma.rb file either from rails default or stolen from another project, and update the Procfile as outlined by Heroku (either calling `puma` or straight up `rails s`)

With the system tests PR merged, removing the line that forces capybara to run webrick should be done too.
