### ISSUE TITLE
Sitemap endpoint broken

### ISSUE THREAD

**Issue by t27duck** [indyhackers/indyhackers.org#113]
Is `/sitemap.xml` supposed to work? It's referencing a `Post` constant that does not exist in the app.

**Comment by mileszs** [comment]
Looks like this was fixed eventually. https://github.com/indyhackers/indyhackers.org/pull/120/files#diff-2b6b9e46fc6dd06b07123b9eb7ed5691f7898d31199d3f8978345986d80b9f67
