### ISSUE TITLE
"Subscribe to the Events Feed" link is broken

### ISSUE THREAD

**Issue by wakproductions** [indyhackers/indyhackers.org#25]
On the home page, the link "Subscribe to the Events Feed" link above the calendar leads to a 403 forbidden error

https://www.google.com/calendar/feeds/ig7e0j6v8ub9q6kga256n77048%40group.calendar.google.com/public/basic

**Comment by netshade** [comment]
This should now be fixed, thanks @wakproductions

**Comment by netshade** [comment]
Fixed by #31
