### ISSUE TITLE
IndyHackers logo misaligned on Code of Conduct

### ISSUE THREAD

**Issue by netshade** [indyhackers/indyhackers.org#61]
![indyhackers-logomisalignment](https://user-images.githubusercontent.com/3809/26885915-f0256dcc-4b71-11e7-9fe4-a47c92fe56ac.png)

cc @illbzo1 , misalignment appears on `/coc/` and `/code-of-conduct/`

**Comment by illbzo1** [comment]
@netshade yeah, noticed this earlier today. I suspect those pages are using a different CSS file which wasn't updated. I'll take a look tonight and push a fix.

**Comment by netshade** [comment]
Fixed by #62
