### ISSUE TITLE
Miles/Swanson pictures are misaligned on Jobs page

### ISSUE THREAD

**Issue by netshade** [indyhackers/indyhackers.org#63]
See [this OurHealth listing](http://www.indyhackers.org/jobs/senior-software-engineer-at-ourhealth)

![indyhackersvisualbug](https://user-images.githubusercontent.com/3809/26959353-c27aa888-4c9d-11e7-85bf-3e1906102042.png)

**Comment by mileszs** [comment]
Honestly should probably stop saying it's only Matt and I, anyway. I don't
know what we should put there, though. Newsletter signup?

**Comment by netshade** [comment]
That'd work - newsletter and link to the current Slack signup page?
