### ISSUE TITLE
Why Indy page needs text color changed to be visible on dark background photo

### ISSUE THREAD

**Issue by mrchameleon** [indyhackers/indyhackers.org#84]
We noticed this and thought we would call it out

[Link to the page where text is unreadable](http://www.indyhackers.org/why_indy)

Edit: The link is not linked from the site anywhere, though it is discoverable via google search

**Comment by mileszs** [comment]
Thank you for calling this out. I would vote we remove this page at this time.

**Comment by mileszs** [comment]
Closed in #185!
